const stockProductos = [
    {
      id: 1,
      nombre: "Playera negra",
      cantidad: 1,
      desc: "Casual",
      precio: 1200,
      img: "./Assets/1.jpg",
    },
    {
      id: 2,
      nombre: "Camisa vaquera",
      cantidad: 1,
      desc: "Casual",
      precio: 1500,
      img: "Assets/2.jpg",
    },
    {
      id: 3,
      nombre: "Blusa beige",
      cantidad: 1,
      desc: "Casual",
      precio: 1570,
      img: "Assets/3.jpg",
    },
    {
      id: 4,
      nombre: "Blusa rayada",
      cantidad: 1,
      desc: "Casual",
      precio: 1000,
      img: "Assets/4.jpg",
    },
    {
      id: 5,
      nombre: "Blusa azul",
      cantidad: 1,
      desc: "Casual",
      precio: 1200,
      img: "Assets/5.jpg",
    },
    {
      id: 6,
      nombre: "Chaqueta multicolor",
      cantidad: 1,
      desc: "Casual",
      precio: 1200,
      img: "Assets/6.jpg",
    },
    {
      id: 7,
      nombre: "Playeras unitalla",
      cantidad: 1,
      desc: "No compres esto por tu bien",
      precio: 1400,
      img: "Assets/8.jpg",
    },
    {
      id: 8,
      nombre: "Blusa hippie",
      cantidad: 1,
      desc: "Casual",
      precio: 1200,
      img: "Assets/11.jpg",
    },
    {
      id: 9,
      nombre: "Blusa casual",
      cantidad: 1,
      desc: "Casual",
      precio: 1400,
      img: "Assets/12.jpg",
    },
    {
      id: 10,
      nombre: "Top casual",
      cantidad: 1,
      desc: "Casual",
      precio: 1200,
      img: "Assets/10.jpg",
    },
  ];

  export default {stockProductos};